cognitive-complexity-threshold = 20
blacklisted-names = ["foo", "too"]
enum-variant-name-threshold = 3
single-char-binding-names-threshold = 0
too-many-arguments-threshold = 3
# pedantic (for these configs you have to provide `#[warn(clippy::pedantic)]` in you bin or lib file)
max-fn-params-bools = 3
max-struct-bools = 3
too-many-lines-threshold = 25

