max_width = 100
tab_spaces = 4
merge_derives = true
reorder_imports = true
fn_args_layout = "Compressed"
hard_tabs = false
reorder_modules = true
use_field_init_shorthand = true

# max_width:
# Represents maximum width of each line.
# Default value: 100
# Input type: unsigned integer
# Example: max_width = 80    // sets 80 chars as a maximum width
# 
# tab_spaces:
# Denotes number of tabs.
# Default value: 4
# Input type: unsigned integer
# Example: tab_spaces = 4    // sets 4 tab spaces as a maximum

# reorder_imports:
# Responsible for reordering imports in a lexicographical order.
# Default value: true
# Input type: boolean
# Example: reorder_imports = false    // denies for reorder imports 

# merge_derives:
# Merge multiple derives into a single one. 
# Default value: true
# Input type: boolean
# Example: merge_derives = false    // disables for merge derive

# fn_args_layout:
# Represents the layout of parameters in a function signature.
# Default value: “Tall”
# Input type: "Compressed", “Tall”, “Vertical”
# Example: merge_derives = “Compressed”    // allows layout of parameters in compressed form

# hard_tabs:
# Responsible for allowing/denying of tab spaces.
# Default value: false
# Input type: boolean
# Example: hard_tabs = true    // allows to set tab spaces

# reorder_modules:
# Helps to reorder modules in a lexicographical manner.
# Default value: true
# Input type: boolean
# Example: reorder_modules = false    //  disables the ordering of modules

# use_field_init_shorthand:
# Allow us to use field initialization in a compact way.
# Default value: false
# Input type: boolean
# Example: use_field_init_shorthand = true    //  allows field initialization
